hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("HYPRSHOT_DIR", "/home/satont/Screenshots")
hl.env("GTK_THEME", "adw-gtk3-dark")
hl.env("WEBKIT_DISABLE_COMPOSITING_MODE", "1")
hl.env("SSH_AUTH_SOCK", "/run/user/1000/gcr/ssh")
