hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.config/hypr/xdg.sh")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("xwaylandvideobridge")
    hl.exec_cmd("waybar & swaync")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("[workspace 1 silent] zen-browser")
    hl.exec_cmd("[workspace 10 silent] Telegram")
    hl.exec_cmd("[workspace 10 silent] discord")
    hl.exec_cmd("[workspace 8 silent] throne")
    hl.exec_cmd("[workspace 7 silent] thunderbird")
    hl.exec_cmd("polychromatic-tray-applet")
    hl.exec_cmd("ags")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme \"adw-gtk3-dark\"")
    hl.exec_cmd("gsettings set org.cinnamon.desktop.default-applications.terminal exec " .. TERMINAL)
end)
