[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"


[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\r"

[window]
opacity = 0.6

[terminal]
